# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'loc = "https://github.com/JuliaString"; mit = "ModuleInterfaceTools"; mh3 = "MurmurHash3"; sb = "StrBase"; la = ("StrAPI", "CharSetEncodings", "ChrBase"); if VERSION < v"0.7.0-DEV.5183"; cln(a)=Pkg.clone("$loc/$a.jl"); cln(mit); cln(mh3); for n in la; Pkg.add(n); end; cln(sb); Pkg.clone(pwd()); else; using Pkg; cln(a)=Pkg.add("$loc/$a.jl"); cln(mit); cln(mh3); for n in la; cln(n); end; cln(sb); pkg"status"; pkg"instantiate"; end; Pkg.test("StrLiterals"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("StrLiterals")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("StrLiterals")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
